//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROUP6_ANGAT.Pages
{


    public partial class HanapGawa
    {

        /// <summary>
        /// pnlServiceApplyMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlServiceApplyMessage;

        /// <summary>
        /// lblServiceApplyMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblServiceApplyMessage;

        /// <summary>
        /// rptServices control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptServices;

        /// <summary>
        /// phServiceLoggedIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phServiceLoggedIn;

        /// <summary>
        /// btnRequestService control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRequestService;

        /// <summary>
        /// phServiceLoggedOut control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phServiceLoggedOut;

        /// <summary>
        /// hfServiceId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfServiceId;

        /// <summary>
        /// hfServiceTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfServiceTitle;

        /// <summary>
        /// hfServiceLocation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfServiceLocation;

        /// <summary>
        /// hfServiceRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfServiceRate;

        /// <summary>
        /// hfServiceTags control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfServiceTags;

        /// <summary>
        /// hfServiceDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfServiceDesc;
    }
}
