//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROUP6_ANGAT
{


    public partial class PostNegosyo
    {

        /// <summary>
        /// pnlPostMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPostMessage;

        /// <summary>
        /// lblPostMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPostMessage;

        /// <summary>
        /// txtBusinessName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBusinessName;

        /// <summary>
        /// ddlCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        /// <summary>
        /// txtBarangay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBarangay;

        /// <summary>
        /// txtAddressLine control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddressLine;

        /// <summary>
        /// txtOwnerName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOwnerName;

        /// <summary>
        /// txtHours control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHours;

        /// <summary>
        /// txtTags control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTags;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// btnPostNegosyo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPostNegosyo;
    }
}
