//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROUP6_ANGAT
{


    public partial class PostService
    {

        /// <summary>
        /// pnlPostMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPostMessage;

        /// <summary>
        /// lblPostMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPostMessage;

        /// <summary>
        /// txtServiceTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtServiceTitle;

        /// <summary>
        /// ddlCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        /// <summary>
        /// txtServiceLocation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtServiceLocation;

        /// <summary>
        /// txtBarangay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBarangay;

        /// <summary>
        /// txtRateMin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRateMin;

        /// <summary>
        /// txtRateMax control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRateMax;

        /// <summary>
        /// ddlRateUnit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRateUnit;

        /// <summary>
        /// txtServiceTags control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtServiceTags;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// txtDateLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateLabel;

        /// <summary>
        /// txtServiceDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtServiceDescription;

        /// <summary>
        /// btnPostService control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPostService;
    }
}
