//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROUP6_ANGAT
{


    public partial class PostJob
    {
        
        /// <summary>
        /// pnlPostMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPostMessage;
        
        /// <summary>
        /// lblPostMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPostMessage;
        
        /// <summary>
        /// txtJobTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtJobTitle;
        
        /// <summary>
        /// ddlCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        
        /// <summary>
        /// txtJobLocation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtJobLocation;
        
        /// <summary>
        /// txtBarangay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBarangay;
        
        /// <summary>
        /// txtPayMin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPayMin;
        
        /// <summary>
        /// txtPayMax control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPayMax;
        
        /// <summary>
        /// ddlPayUnit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPayUnit;
        
        /// <summary>
        /// txtJobTags control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtJobTags;
        
        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        
        /// <summary>
        /// txtDateLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateLabel;
        
        /// <summary>
        /// txtJobDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtJobDescription;
        
        /// <summary>
        /// btnPostJob control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPostJob;
    }
}
