//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROUP6_ANGAT
{


    public partial class Profile
    {
        
        /// <summary>
        /// imgProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgProfile;
        
        /// <summary>
        /// lblProfileName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProfileName;
        
        /// <summary>
        /// lblProfileRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProfileRole;
        
        /// <summary>
        /// lblProfileEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProfileEmail;
        
        /// <summary>
        /// fuProfileImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuProfileImage;
        
        /// <summary>
        /// btnUploadPhoto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUploadPhoto;
        
        /// <summary>
        /// lblProfileMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProfileMessage;
        
        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        
        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        
        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        
        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        
        /// <summary>
        /// txtBarangay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBarangay;
        
        /// <summary>
        /// txtBio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBio;
        
        /// <summary>
        /// btnSaveProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
        
        /// <summary>
        /// txtCurrentPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;
        
        /// <summary>
        /// txtNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        
        /// <summary>
        /// txtConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        
        /// <summary>
        /// btnChangePassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
        
        /// <summary>
        /// lblPasswordMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPasswordMessage;

        /// <summary>
        /// pnlApplicationsMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlApplicationsMessage;

        /// <summary>
        /// lblApplicationsMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblApplicationsMessage;

        /// <summary>
        /// pnlNoApplications control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoApplications;

        /// <summary>
        /// rptApplications control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptApplications;

        /// <summary>
        /// pnlServiceMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlServiceMessage;

        /// <summary>
        /// lblServiceMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblServiceMessage;

        /// <summary>
        /// pnlNoServiceRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoServiceRequests;

        /// <summary>
        /// rptServiceRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptServiceRequests;

        /// <summary>
        /// pnlNoListings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoListings;

        /// <summary>
        /// rptMyListings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptMyListings;

        /// <summary>
        /// pnlNoServiceListings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoServiceListings;

        /// <summary>
        /// rptServiceListings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptServiceListings;
    }
}
